image: docker.fslab.de/rhartm2m/praktomat_hbrs


stages:
    - committest


before_script:
    #- sudo apt-get install git -y -q
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - git config --global user.name "Robert Hartmann - Gitlab FSLab"
    - git config --global user.email "Robert.Hartmann@h-brs.de"
    - git remote -v
    #- lsb_release -a
    #- sudo apt-get autoclean -y -q
    #- sudo apt-get autoremove --purge -y -q
    #- sudo apt-get update -y -q
    #- sudo apt-get install linux-headers-$(uname -r) -y -q
    #- sudo apt-get install apt build-essential git openssl  libsasl2-dev libssl-dev libpq-dev -y -q --no-install-recommends apt-utils
    #- sudo apt-get install libldap2-dev -y -q
    #- sudo apt-get install python-pip python-virtualenv python2.7-dev swig -y -q
    #- sudo apt-get install sqlite3 -y -q
    #- sudo apt-cache search java | grep openjdk
    #- sudo apt-get install openjdk-8-jdk dejagnu checkstyle gcj-jdk -y -q
    #- sudo update-java-alternatives -s java-1.8.0-openjdk
    
    #- sudo apt-get install wget phantomjs -y -q
    
    #- sudo apt-get install r-base -y -q
    #- sudo apt-get autoclean -y -q
    #- sudo apt-get autoremove -y -q
    #- sudo apt-get clean -y -q
    - sqlite3 --version
    - python2 --version
    - python3 --version
#    - sudo apt-get install python  python3 ipython python3-requests python-pip python3-pip python-virtualenv python2.7-dev python3.5-dev python3-six python-six swig -y -q
    - pip --version
    - pip3 --version
    - swig -version
    - openssl version
    - ls /usr/bin/python*
    - virtualenv -p python3.5 py3env
    - virtualenv -p python2.7 py2env
    
    - . py2env/bin/activate
    - python --version
    - pip --version
    - which pip
    #- wget https://gist.github.com/ManuelTS/935155f423374e950566d05d1448038d/raw/906887cbfa384d450276b87087d28e6a51245811/install_phantomJs.sh
    #- chmod u+x ./install_phantomJs.sh
    #- sudo ./install_phantomJs.sh
    - export QT_QPA_PLATFORM=phantom
    - phantomjs --version
    
    - pip install -U pip virtualenv setuptools wheel urllib3[secure]
#    - pip install M2Crypto==0.30.1
    - pip install M2Crypto
    - pip install https://pypi.python.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d41b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz#md5=824c801e479d3e916879aae3e9c15e16
    - pip install -r requirements.txt
    - pip install reindent
    - deactivate

    - . py3env/bin/activate
    - python --version
    - which pip
    - which pip3
    - pip --version
    - pip3 --version
    #- wget https://gist.github.com/ManuelTS/935155f423374e950566d05d1448038d/raw/906887cbfa384d450276b87087d28e6a51245811/install_phantomJs.sh
    #- chmod u+x ./install_phantomJs.sh
    #- sudo ./install_phantomJs.sh
    - export QT_QPA_PLATFORM=phantom
    - phantomjs --version
    
    - pip3 install -U pip virtualenv setuptools wheel urllib3[secure]
#    - pip install M2Crypto==0.30.1
    - pip3 install M2Crypto
    #- pip3 install https://pypi.python.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d41b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz#md5=824c801e479d3e916879aae3e9c15e16
    - pip3 install -r requirements.txt
    - pip3 install reindent
    - wget https://raw.githubusercontent.com/certik/python-3.2/master/Tools/scripts/reindent.py -O ./py3env/lib/python3.5/site-packages/reindent.py
    - deactivate

test 1:2
   stage: committest
   script:
    - mkdir -p data
    - ls -la .
    - . py2env/bin/activate
    - ./src/manage-test.py makemigrations
    - ./src/manage-test.py test accounts attestation checker configuration solutions tasks

test 2:2
   stage: committest
   script:
    - mkdir -p data
    - ls -la .
    - . py3env/bin/activate
    - ./src/manage-test.py makemigrations
    - ./src/manage-test.py test accounts attestation checker configuration solutions tasks
    
