stages:
    - committest
    - mergetest

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - lsb_release -a
    - sudo apt-get autoclean -y -q
    - sudo apt-get autoremove --purge -y -q
    - sudo apt-get update -y -q
    - sudo apt-get install linux-headers-$(uname -r) -y -q
    - sudo apt-get install apt build-essential git openssl  libsasl2-dev libssl-dev libpq-dev -y -q --no-install-recommends apt-utils
    - sudo apt-get install libldap2-dev -y -q
    - sudo apt-get install python-pip python-virtualenv python2.7-dev swig -y -q
    - sudo apt-get install sqlite3 -y -q
    - sudo apt-cache search java | grep openjdk
    - sudo apt-get install openjdk-8-jdk dejagnu checkstyle gcj-jdk -y -q
    - sudo update-java-alternatives -s java-1.8.0-openjdk
    
    - sudo apt-get install wget phantomjs -y -q
    
    - sudo apt-get install r-base -y -q
    - sudo apt-get autoclean -y -q
    - sudo apt-get autoremove -y -q
    - sudo apt-get clean -y -q
    - sqlite3 --version
    - python --version
    - pip install pip
    - pip --version
    - swig -version
    - openssl version
    - virtualenv env
    - . env/bin/activate
    
    - wget https://gist.github.com/ManuelTS/935155f423374e950566d05d1448038d/raw/906887cbfa384d450276b87087d28e6a51245811/install_phantomJs.sh
    - chmod u+x ./install_phantomJs.sh
    - sudo ./install_phantomJs.sh
    - export QT_QPA_PLATFORM=phantom
    - phantomjs --version
    
    - pip install -U pip virtualenv setuptools wheel urllib3[secure]
    - pip install M2Crypto==0.30.1
    - pip install https://pypi.python.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d41b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz#md5=824c801e479d3e916879aae3e9c15e16
    - pip install -r requirements.txt

test:
   stage: committest
   script:
    - mkdir data
    - ls -la .
    - ./src/manage-test.py makemigrations
    - ./src/manage-test.py test accounts attestation checker configuration solutions tasks
    
    
masterToMaster:
   before_script: 
   - echo "merge upstream/master to master"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout master
    - git merge upstream/master

masterToLDAP:
   before_script: 
   - echo "merge upstream/master to feature_LDAP"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_LDAP_bindings
    - git merge upstream/master

masterToContactlink:
   before_script: 
   - echo "merge upstream/master to feature_Contactlink"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_disable_contactlink
    - git merge upstream/master

masterToSolutiondetails:
   before_script: 
   - echo "merge upstream/master to feature_Solutiondetails"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_download_solutiondetails
    - git merge upstream/master
    
masterToTypos:
   before_script: 
   - echo "merge upstream/master to Typos"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout bugfix_small_typos
    - git merge upstream/master
    
masterToButtonModellSolution:
   before_script: 
   - echo "merge upstream/master to ButtonModellSolution"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_TaskAdmin_Button_Modell_Solution
    - git merge upstream/master
    

masterToSortTask:
   before_script: 
   - echo "merge upstream/master to SortTask"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_sort_tasklist_via_names
    - git merge upstream/master
    
masterToWaitTime:
   before_script: 
   - echo "merge upstream/master to WaitTime"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_dynamic_upload_waiting_time
    - git merge upstream/master
    
masterToWatchSolutionFiles:
   before_script: 
   - echo "merge upstream/master to WatchSolutionFiles"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_TrainerTutor_Watch_SolutionFiles
    - git merge upstream/master
    
masterToResubmitFix:
   before_script: 
   - echo "merge upstream/master to ResubmitFix"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout bugfix_solution_resubmit
    - git merge upstream/master
    
masterToAvoidDBshell:
   before_script: 
   - echo "merge upstream/master to AvoidDBshell"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_admin-additional-actions_avoid_working_via_dbshell
    - git merge upstream/master
    
masterToAutoattestChecker:
   before_script: 
   - echo "merge upstream/master to AutoattestChecker"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_autoattestchecker
    - git merge upstream/master
    
masterToDiffChecker:
   before_script: 
   - echo "merge upstream/master to DiffChecker"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_diffchecker
    - git merge upstream/master
    
masterToSafeexec:
   before_script: 
   - echo "merge upstream/master to Safeexec"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout bugfix_safeexec
    - git merge upstream/master
    
masterToHttpProxy:
   before_script: 
   - echo "merge upstream/master to HttpProxy"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_gitmodules_https-proxy_compatible
    - git merge upstream/master
    
masterToCUnitCPPunit:
   before_script: 
   - echo "merge upstream/master to CUnitCppUnitChecker"
   stage: mergetest
   script:
    - git remote add -t master -m master -f upstream https://github.com/KITPraktomatTeam/Praktomat.git
    - git checkout feature_CUnitCppUnit_Checker
    - git merge upstream/master
        
    
    
    