name: Trigger GitLab Docker CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI
        run: |
          curl -X POST https://gitlab.itsec.ur.de/api/v4/projects/4242/trigger/pipeline \
            -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -F ref=main
